services:
  www:
    image: leaguesphere/frontend:latest
    container_name: ${COMPOSE_PROJECT_NAME}.www
    labels:
      # redirect service
      # https://jensknipper.de/blog/traefik-http-to-https-redirect/
      - traefik.http.routers.${SERVICE_NAME}-http.entrypoints=web
      - traefik.http.routers.${SERVICE_NAME}-http.rule=Host(`leaguesphere.app`) || Host(`www.leaguesphere.app`)
      - traefik.http.routers.${SERVICE_NAME}-http.middlewares=${SERVICE_NAME}-https
      - traefik.http.middlewares.${SERVICE_NAME}-https.redirectscheme.scheme=https

      # true service
      - traefik.http.routers.${SERVICE_NAME}.tls=true
      - traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SERVICE_HOST}`)
      - traefik.http.routers.${SERVICE_NAME}.tls.certresolver=letsencryptdnsresolver

      # prod resolver
      - traefik.http.routers.${SERVICE_NAME}_prod.tls=true
      - traefik.http.routers.${SERVICE_NAME}_prod.rule=Host(`leaguesphere.app`) || Host(`www.leaguesphere.app`)

      # local service
      - traefik.http.routers.${SERVICE_NAME}_prod.tls.certresolver=letsencrypthttpresolver
      - traefik.http.routers.${SERVICE_NAME}_local_qualified.rule=Host(`${SERVICE_NAME}.${LOCAL_HOSTNAME}`)
      - traefik.http.routers.${SERVICE_NAME}_local_qualified.entrypoints=web
    networks:
      - backend
      - proxy
    depends_on:
      app:
        condition: service_healthy
    healthcheck:
      test: curl -A healthcheck -I --fail http://localhost || exit 1
    restart: unless-stopped

  app:
    image: leaguesphere/backend:latest
    container_name: ${COMPOSE_PROJECT_NAME}.app
    command: gunicorn -b 0.0.0.0:8000 league_manager.wsgi
    environment:
      MYSQL_HOST: db
      MYSQL_DB_NAME: ${MYSQL_DB_NAME}
      DJANGO_SETTINGS_MODULE: league_manager.settings.dev
      SECRET_KEY: ${SECRET_KEY}
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: curl -A healthcheck -I --fail http://localhost:8000 || exit 1

  db:
    restart: unless-stopped
    image: mariadb:lts
    container_name: ${COMPOSE_PROJECT_NAME}.db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-storage-engine=InnoDB
    volumes:
      - "./database:/var/lib/mysql"
    networks:
      - backend
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    healthcheck:
      test: healthcheck.sh --connect --innodb_initialized
      start_period: 5s

volumes:
  static:

networks:
  backend:
  proxy:
    external: true
